services:
  todo-vue:
    container_name: todo-vue
    build: "./docker/nodejs"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  todo-api:
    container_name: todo-vue-api
    working_dir: /app
    image: "ghcr.io/remimichel/todo-api:v0.0.1"
    command: python main.py
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"

  database:
    container_name: database
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password